version: "3"

services:

  app:
    container_name: t-ret
    image: template_ret
    build:
      context: ./
    ports:
      - "5000:5000"
    working_dir: /app
    command: flask run --host=0.0.0.0
#    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - as

networks:
  as:
    driver: bridge
